# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(to='crm.Role'),
        ),
    ]
