# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
