# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='default_email', max_length=60),
            preserve_default=False,
        ),
    ]
