# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='admin_column',
            field=models.EmailField(default='admin_column_test', max_length=20),
            preserve_default=False,
        ),
    ]
