# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
