# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180103_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'OpenStack'), (2, 'Linux')], default=0),
            preserve_default=False,
        ),
    ]
