# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='english',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
