# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_application_hosttoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='app',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='host',
        ),
        migrations.AddField(
            model_name='application',
            name='relation',
            field=models.ManyToManyField(to='app01.Host'),
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
